### ISSUE TITLE
My Contact Information

### ISSUE THREAD

**Issue by HimeaZhao** [HimeaZhao/mktorrent_crc#2]
QQ 1463184901

**Comment by scientihark** [comment]
pt贴吧看到的

不太会写c
不知道nodejs 可不可以

说下我理解的这个程序的意图
既然是为了方便辅种
那么
我们假设既有资源目录为A 种子为torrentA
目标整理路径为B 种子为torrentB

现在要做的是对A目录中的文件逐一Hash
然后比对其在torrentB中是否有对应文件
若有就将其从A目录按照torrentB中描述的路径和文件名放置到B目录中 

是这个意思吧

nodejs可以的话我可以写nodejs版的

**Comment by fyzzy1943** [comment]
原来是这样 0 0

**Comment by scientihark** [comment]
不过torrent内本身就有hash值了 不需要额外CRC呢
直接指定源目录 目标种子和整理后目录就可以了

**Comment by scientihark** [comment]
正在尝试用node写

**Comment by fyzzy1943** [comment]
所以说最终目标是建立一个本地仓库嘛？

**Comment by scientihark** [comment]
辅种用的小工具 目测

**Comment by HimeaZhao** [comment]
torrent 里没有hash值啊，我从源码看只有对块hash，并没单文件hash

（nodejs要怎么用呢，昨天我在看node-mktorrent源码，最后发现本地浏览器上根本无法执行的样子

**Comment by fyzzy1943** [comment]
我想知道种子文件现在有标准嘛？

**Comment by scientihark** [comment]
有的
种子内的确只有块大小
但是我想的是这个工具最好标准种子也能用

**Comment by scientihark** [comment]
种子内记录了文件大小的 可以按照顺序找到每个文件 x字节到y字节间的hash

**Comment by scientihark** [comment]
我画张图 举个例子

**Comment by fyzzy1943** [comment]
会存在一个块 跨两个文件的情况嘛？

**Comment by scientihark** [comment]
首先是对于幼儿园最多的原盘中常见的大于块大小2倍以上的文件的处理
![1](https://cloud.githubusercontent.com/assets/1818921/13765671/6ae5e7fa-ea96-11e5-9f69-4f46d6f09f3d.jpg)

图上为一个种子
有3个文件
若干个固定大小的块

我们从第一个文件开始找
首先 查看当前文件的开头在哪个块里
如果开头的位置在一个块的起始 文件大小大于块大小 那么使用这个块作为文件识别hash块
如果开头位置不再起始那么使用下一个块作为识别hash块

**Comment by scientihark** [comment]
对于小文件就比较复杂了

**Comment by scientihark** [comment]
首先将大文件确定后
按照文件大小进行粗略比对 确定其大概在那些块内
比对不上的 自然这两个文件hash不同
比对上的 （包括同大小的文件）按照可能逐一hash
由于这部分都是小文件
除非小文件特别多的包  hash处理3个块大小（加起来一般1m以内）  是很快的

**Comment by fyzzy1943** [comment]
不过话说回来，这个程序应对的场景是A种包含文件1/2/3，B种包含2/3/4的情况嘛？这种情况是不是 不是很常见呀。

**Comment by scientihark** [comment]
按照一般情况  文件的某个部分的hash对上就可以粗略看成文件一致了
然后全部匹配完成后可以进行完整的hash   匹配率100%的文件就可以辅种了

**Comment by scientihark** [comment]
整个逻辑我想的是这样的

关于之前的node的问题
node可以在win linux osx上运行
可以作为命令行工具
也可以带ui

**Comment by fyzzy1943** [comment]
@scientihark 如果文件的分块位置不同 hash是不是也不一样了

**Comment by scientihark** [comment]
是的

**Comment by scientihark** [comment]
所以不能用源种子来玩

**Comment by scientihark** [comment]
源种子没想到什么好用处目前

**Comment by scientihark** [comment]
顺带求一发幼儿园邀
![1](https://cloud.githubusercontent.com/assets/1818921/13765922/a799cbba-ea98-11e5-893f-47343a2ff2bb.jpg)
![2](https://cloud.githubusercontent.com/assets/1818921/13765923/a7c9ecaa-ea98-11e5-8d77-0e2981018a62.jpg)
![111](https://cloud.githubusercontent.com/assets/1818921/13765925/a7f8ecbc-ea98-11e5-9e5a-900e872bb38e.jpg)
![222](https://cloud.githubusercontent.com/assets/1818921/13765924/a7f89d98-ea98-11e5-884c-5e154fa2770e.jpg)
![img_20151223_165506](https://cloud.githubusercontent.com/assets/1818921/13765926/a7fa17d6-ea98-11e5-906b-c91151ff48b4.jpg)

年前想求 结果 貌似封闭了好久

**Comment by fyzzy1943** [comment]
卧槽好多光盘

**Comment by scientihark** [comment]
我都收原盘的 全是蓝光
不过天使上拉的很多就是了

**Comment by fyzzy1943** [comment]
所以现在的结论就是：在目前流行的种子格式下，无法区分出文件。所以想要区分出文件，就必然要修改种子格式。但是。。。

**Comment by scientihark** [comment]
就是天使上看到的@U2系列的种子 发现了幼儿园这个神奇的地方

可以区分啊  我刚刚的算法分析在上面了

**Comment by scientihark** [comment]
修改种子不是很推荐   有些pt站会自己改种子  你的crc就gg了

**Comment by fyzzy1943** [comment]
我刚才说了呀。每个文件的分块未必相同，分块不同，你按分块识别 就识别不出来呀

**Comment by fyzzy1943** [comment]
虽然是同一个文件

**Comment by scientihark** [comment]
我又没按分块识别

我是按照目标种子里写的分块大小处理的

**Comment by scientihark** [comment]
和原种子怎么分无关

**Comment by scientihark** [comment]
文件都是完整的

**Comment by scientihark** [comment]
原种子256k一分    下回来你还是5G完整的一个文件
我现在把这个5G文件按照目标种子的分块 512k一分来计算hash  冰没有什么问题

**Comment by scientihark** [comment]
只hash 少量文件块来完成文件匹配    可以很快识别文件  很多同步工具都是这样做的
最终结果前仔细hash一次就行了  
甚至可以直接把整理得到的目录交给utorrent校验

**Comment by scientihark** [comment]
权贵大大不加我QQ 不开森

**Comment by HimeaZhao** [comment]
那个  分段hash版的已经有了

然而对于圆盘这种一堆小文件的，没有任何意义

crc 系统是为 https://www.snowpt.com/ 准备的，不管其他pt站的

**Comment by coeusite** [comment]
我不太明白…torrent里标准的hash是按piece记录的，你不可能通过其计算出每一个单独文件的hash值，顶多是用其确定一部分拥有完整piece的大文件，而且还不能保证头尾都正确。

与此同时，部分种子可能会额外包含每个文件的crc/md5/sha1数值，如果有的话，直接拿 文件长度+额外hash 在数据库里查不就行了么？

**Comment by coeusite** [comment]
而且即便是大文件，如果不是100%匹配，也是不应该直接软链的。应该复制后，在client里完成下载，再比对文件hash，删除相同的文件并用软链代替。

**Comment by HimeaZhao** [comment]
没错，其实算法就是一个size／crc查找

**Comment by coeusite** [comment]
这个不是很简单么…
建立数据库（用size排序）、查(size,crc)、输出文件地址、做软链

而且据说数据库你已经建好了 ˊ_>ˋ

至于parse torrent, python里几行代码的事儿。

**Comment by scientihark** [comment]
nodejs 版本done
正在打包
包含crc种子的生成和按照此类种子对目录整理硬链接的功能

**Comment by scientihark** [comment]
win版  linux 和osx请看压缩包内readme
[nodeTorrentHash.zip](https://github.com/HimeaZhao/mktorrent_crc/files/175405/nodeTorrentHash.zip)

**Comment by scientihark** [comment]
新版本
https://github.com/scientihark/sthelper/releases/tag/v0.0.4
昨天缺依赖问题解决了
在npm里装不会有问题了
